### ISSUE TITLE
Nooby question - Can you see any easy way i can reconfigure this verifier to simply verify a secp256k1 signature, a message that was signed and public key who signed, returning a true false if valid? 

### ISSUE THREAD

**Issue by crokau** [DucaturFw/ether-schnorr-verification#1]
Im trying to verify a signature from a schnorr based blockchain in ethereum, it would be awesome if the contract itself could verify the signature is true.

I get confused in your tests where you have these variables:

        // random point x,
        bn("016..."),
        // random point y
        bn("2af..."),
        // group key x,
        bn("2b1f1..."),
        ...

can you briefly explain how this verification method relates to a simple verification method with 3 variables like this?

[ 
  "message that was signed", 
  "secp256k1 signature", 
  "public key who signed" 
]  

EXAMPLE in js

```
const isValidSignature = async (signedMessage, signature, address) => {
        const publicKey = decodeAddress(address);
        const hexPublicKey = u8aToHex(publicKey);
        console.log(hexPublicKey)
        return signatureVerify(signedMessage, signature, address);
      
    };
      
    cryptoWaitReady().then(() => {
        const isValid = isValidSignature(
            'abc',
          '0x68bffce3d1cb502bf0aa496475f8202b8ac34ad0b5a29503c0a83f1fc58cd620914a52207091e229726507db092c6a9f7355c2056420b9b13e5746eead55e487',
            '5EJJe8JkehPGXukzjAs1fUnhPoBrcWTjv2Z5Zw859iHoTKXX'
        );
        console.log(isValid)
    });

```

Thanks for any help,

Just trying to get my head around new things.

**Comment by Lizard-King101** [comment]
@spaceforce-dev did you ever figure this out?? what was your findings i'm trying to do the same thing but cant find the equivalent varification on the ethereum smart contract.
